# Generated by Django 2.2.12 on 2022-01-29 08:43

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('aas140', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_mobile',
            field=otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
    ]
