# Generated by Django 2.2.12 on 2022-01-29 10:43

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('aas140', '0002_player_is_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='is_mobile',
            field=otree.db.models.IntegerField(null=True),
        ),
    ]
