# Generated by Django 2.2.12 on 2022-01-29 10:51

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('aas140', '0003_auto_20220129_1843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='is_mobile',
        ),
        migrations.AddField(
            model_name='player',
            name='IsMobile',
            field=otree.db.models.IntegerField(null=True),
        ),
    ]
