# Generated by Django 2.2.12 on 2022-03-04 09:06

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('aas140', '0004_auto_20220129_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='Prolific_id',
            field=otree.db.models.StringField(default=' ', max_length=10000, null=True),
        ),
    ]
