# Generated by Django 2.2.12 on 2022-01-29 11:52

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('bam122', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_mobile',
            field=otree.db.models.IntegerField(null=True),
        ),
    ]
