# Generated by Django 2.2.12 on 2022-03-09 06:55

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('bam122', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='AC_Q5',
            field=otree.db.models.StringField(blank=0, choices=[('Very Dark', 'Very Dark'), ('Dark', 'Dark'), ('Slightly Dark', 'Slightly Dark'), ('Average/Neutral', 'Average/Neutral'), ('Slightly Fair', 'Slightly Fair'), ('Fair', 'Fair'), ('Very Fair', 'Very Fair')], max_length=10000, null=True, verbose_name='Dark'),
        ),
        migrations.AddField(
            model_name='player',
            name='AC_Q6',
            field=otree.db.models.StringField(blank=0, choices=[('Very Underweight', 'Very Underweight'), ('Underweight', 'Underweight'), ('Slightly Underweight', 'Slightly Underweight'), ('Average/Neutral', 'Average/Neutral'), ('Slightly Overweight', 'Slightly Overweight'), ('Overweight', 'Overweight'), ('Very Overweight', 'Very Overweight')], max_length=10000, null=True, verbose_name='Very Overweight'),
        ),
        migrations.AddField(
            model_name='player',
            name='AC_Q7',
            field=otree.db.models.StringField(blank=0, choices=[('Very Feminine', 'Very Feminine'), ('Feminine', 'Feminine'), ('Slightly Feminine', 'Slightly Feminine'), ('Average/Neutral', 'Average/Neutral'), ('Slightly Masculine', 'Slightly Masculine'), ('Masculine', 'Masculine'), ('Very Masculine', 'Very Masculine')], max_length=10000, null=True, verbose_name='Average/Neutral'),
        ),
        migrations.AlterField(
            model_name='player',
            name='AC_Q1',
            field=otree.db.models.StringField(blank=0, choices=[('Very Exogenous', 'Very Exogenous'), ('Exogenous', 'Exogenous'), ('Slightly Exogenous', 'Slightly Exogenous'), ('Average/Neutral', 'Average/Neutral'), ('Slightly Endogenous', 'Slightly Endogenous'), ('Endogenous', 'Endogenous'), ('Very Endogenous', 'Very Endogenous')], max_length=10000, null=True, verbose_name='Exogenous'),
        ),
        migrations.AlterField(
            model_name='player',
            name='AC_Q2',
            field=otree.db.models.StringField(blank=0, choices=[('Very Unversatile', 'Very Unversatile'), ('Unversatile', 'Unversatile'), ('Slightly Unversatile', 'Slightly Unversatile'), ('Average/Neutral', 'Average/Neutral'), ('Slightly Versatile', 'Slightly Versatile'), ('Versatile', 'Versatile'), ('Very Versatile', 'Very Versatile')], max_length=10000, null=True, verbose_name='Versatile'),
        ),
        migrations.AlterField(
            model_name='player',
            name='AC_Q4',
            field=otree.db.models.StringField(blank=0, choices=[('Very Aggressive', 'Very Aggressive'), ('Aggressive', 'Aggressive'), ('Slightly Aggressive', 'Slightly Aggressive'), ('Average/Neutral', 'Average/Neutral'), ('Slightly Friendly', 'Slightly Friendly'), ('Friendly', 'Friendly'), ('Very Friendly', 'Very Friendly')], max_length=10000, null=True, verbose_name='Very Aggressive'),
        ),
    ]
