# Generated by Django 2.2.12 on 2022-01-29 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bam122', '0002_player_is_mobile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='is_mobile',
        ),
    ]
