# Generated by Django 2.2.12 on 2022-03-08 07:13

from django.db import migrations, models
import django.db.models.deletion
import otree.db.idmap
import otree.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('otree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_subsession', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cdd129_group', to='otree.Session')),
            ],
            options={
                'db_table': 'cdd129_group',
            },
            bases=(models.Model, otree.db.idmap.GroupIDMapMixin),
        ),
        migrations.CreateModel(
            name='Subsession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cdd129_subsession', to='otree.Session')),
            ],
            options={
                'db_table': 'cdd129_subsession',
            },
            bases=(models.Model, otree.db.idmap.SubsessionIDMapMixin),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_group', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_payoff', otree.db.models.CurrencyField(default=0, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_role', otree.db.models.StringField(max_length=10000, null=True)),
                ('GameTheoryFamiliar', otree.db.models.IntegerField(blank=1, choices=[[1, 'Yes'], [0, 'No']], null=True, verbose_name='Are you familiar with game theory?')),
                ('AgeCategory', otree.db.models.StringField(blank=1, choices=[('20 and younger', '20 and younger'), ('20 - 29', '20 - 29'), ('30 - 39', '30 - 39'), ('40 - 49', '40 - 49'), ('50 - 59', '50 - 59'), ('60 and older', '60 and older')], max_length=10000, null=True, verbose_name='Which category below includes your age?')),
                ('Gender', otree.db.models.StringField(blank=1, choices=[('Male', 'Male'), ('Female', 'Female'), ('I prefer not to answer', 'I prefer not to answer'), ('Other', 'Other')], max_length=10000, null=True, verbose_name='What is your gender?')),
                ('RaceEthnicity', otree.db.models.StringField(blank=1, choices=[('White or Caucasian', 'White or Caucasian'), ('Black or African American', 'Black or African American'), ('Native American or American Indian', 'Native American or American Indian'), ('Hispanic or Latino', 'Hispanic or Latino'), ('Asian or Pacific Islander', 'Asian or Pacific Islander'), ('Others or Multiracial', 'Others or Multiracial')], max_length=10000, null=True, verbose_name='What is your race/ethnicity?')),
                ('MaritalStatus', otree.db.models.StringField(blank=1, choices=[('Single and never married', 'Single and never married'), ('Cohabiting (or Domestic Partnership)', 'Cohabiting (or Domestic Partnership)'), ('Married', 'Married'), ('Widowed', 'Widowed'), ('Divorced', 'Divorced'), ('Separated', 'Separated')], max_length=10000, null=True, verbose_name='What is your marital status?')),
                ('NumChildren', otree.db.models.StringField(blank=1, choices=[('None', 'None'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5 or more', '5 or more')], max_length=10000, null=True, verbose_name='Do you have any children aged from 0 to 17 living at home with you, or to whom you have regular responsibility for? If so, how many?')),
                ('Employment', otree.db.models.StringField(blank=1, choices=[('Employed for wages', 'Employed for wages'), ('Self-employed', 'Self-employed'), ('Out of work and looking for work', 'Out of work and looking for work'), ('Out of work but not currently looking for work', 'Out of work but not currently looking for work'), ('Homemaker', 'Homemaker'), ('Student', 'Student'), ('Military', 'Military'), ('Retired', 'Retired'), ('Unable to work', 'Unable to work')], max_length=10000, null=True, verbose_name='What is your current employment status?')),
                ('PoliticalOrientation', otree.db.models.StringField(blank=1, choices=[('Very liberal', 'Very liberal'), ('Slightly liberal', 'Slightly liberal'), ('Neutral', 'Neutral'), ('Slightly conservative', 'Slightly conservative'), ('Very conservative', 'Very conservative')], max_length=10000, null=True, verbose_name='What is your political orientation?')),
                ('PoliticalParty', otree.db.models.StringField(blank=1, choices=[('Democratic Party', 'Democratic Party'), ('Republican Party', 'Republican Party'), ('Independent', 'Independent'), ('None of the above', 'None of the above'), ('I prefer not to say', 'I prefer not to say')], max_length=10000, null=True, verbose_name='Which political party do you support?')),
                ('Education', otree.db.models.StringField(blank=1, choices=[('No schooling completed', 'No schooling completed'), ('Nursery school to 8th grade', 'Nursery school to 8th grade'), ('Some high school, no diploma', 'Some high school, no diploma'), ('High school graduate, diploma or equivalent', 'High school graduate, diploma or equivalent'), ('Some college, have a diploma but no degree', 'Some college, have a diploma but no degree'), ('College degree', 'College degree'), ('Master degree', 'Master degree'), ('Doctorate (Ph.D)', 'Doctorate (Ph.D)')], max_length=10000, null=True, verbose_name='What is the highest level of education you have completed?')),
                ('MedicalConditions', otree.db.models.StringField(blank=1, max_length=10000, null=True, verbose_name='Do you have any existing medical conditions prior to the COVID-19 pandemic? If so, please state them. If not, please write "None".')),
                ('Residence', otree.db.models.StringField(blank=1, choices=[('Alabama', 'Alabama'), ('Alaska', 'Alaska'), ('Arizona', 'Arizona'), ('Arkansas', 'Arkansas'), ('California', 'California'), ('Colorado', 'Colorado'), ('Connecticut', 'Connecticut'), ('Delaware', 'Delaware'), ('Florida', 'Florida'), ('Georgia', 'Georgia'), ('Hawaii', 'Hawaii'), ('Idaho', 'Idaho'), ('Illinois', 'Illinois'), ('Indiana', 'Indiana'), ('Iowa', 'Iowa'), ('Kansas', 'Kansas'), ('Kentucky', 'Kentucky'), ('Louisiana', 'Louisiana'), ('Maine', 'Maine'), ('Maryland', 'Maryland'), ('Massachusetts', 'Massachusetts'), ('Michigan', 'Michigan'), ('Minnesota', 'Minnesota'), ('Mississippi', 'Mississippi'), ('Missouri', 'Missouri'), ('Montana', 'Montana'), ('Nebraska', 'Nebraska'), ('Nevada', 'Nevada'), ('New Hampshire', 'New Hampshire'), ('New Jersey', 'New Jersey'), ('New Mexico', 'New Mexico'), ('New York', 'New York'), ('North Carolina', 'North Carolina'), ('North Dakota', 'North Dakota'), ('Ohio', 'Ohio'), ('Oklahoma', 'Oklahoma'), ('Oregon', 'Oregon'), ('Pennsylvania', 'Pennsylvania'), ('Rhode Island', 'Rhode Island'), ('South Carolina', 'South Carolina'), ('South Dakota', 'South Dakota'), ('Tennessee', 'Tennessee'), ('Texas', 'Texas'), ('Utah', 'Utah'), ('Vermont', 'Vermont'), ('Virginia', 'Virginia'), ('Washington', 'Washington'), ('West Virginia', 'West Virginia'), ('Wisconsin', 'Wisconsin'), ('Wyoming', 'Wyoming')], max_length=10000, null=True, verbose_name='In which state do you currently reside?')),
                ('HouseholdIncome', otree.db.models.StringField(blank=1, choices=[('Less than $10,000', 'Less than $10,000'), ('$10,000 - $19,999', '$10,000 - $19,999'), ('$20,000 - $29,999', '$20,000 - $29,999'), ('$30,000 - $39,999', '$30,000 - $39,999'), ('$40,000 - $49,999', '$40,000 - $49,999'), ('$50,000 - $59,999', '$50,000 - $59,999'), ('$60,000 - $69,999', '$60,000 - $69,999'), ('$70,000 - $79,999', '$70,000 - $79,999'), ('$80,000 - $89,999', '$80,000 - $89,999'), ('$90,000 - $99,999', '$90,000 - $99,999'), ('$100,000 - $124,999', '$100,000 - $124,999'), ('$125,000 - $149,999', '$125,000 - $149,999'), ('$150,000 and above', '$150,000 and above')], max_length=10000, null=True, verbose_name='Which category includes your entire household income in the previous year before taxes?')),
                ('InstructionsEasy', otree.db.models.FloatField(blank=1, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], null=True, verbose_name='The instructions for each section were easy to understand.')),
                ('QuestionsEasy', otree.db.models.FloatField(blank=1, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], null=True, verbose_name='The questions in each section were easy to understand.')),
                ('Discomfort', otree.db.models.FloatField(blank=1, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], null=True, verbose_name='The images in the experiment were discomforting.')),
                ('DifficultyComment', otree.db.models.StringField(blank=1, max_length=10000, null=True, verbose_name='Please indicate any part(s) of the experiment which you found difficult to understand. If there are none, please write "None".')),
                ('Feedback', otree.db.models.StringField(blank=1, max_length=10000, null=True, verbose_name='We value the feedback of all our participants. Please leave any comments you may have about the experiment. If you do not wish to comment, please write "None".')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cdd129.Group')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cdd129_player', to='otree.Participant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cdd129_player', to='otree.Session')),
                ('subsession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cdd129.Subsession')),
            ],
            options={
                'db_table': 'cdd129_player',
            },
            bases=(models.Model, otree.db.idmap.PlayerIDMapMixin),
        ),
        migrations.AddField(
            model_name='group',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cdd129.Subsession'),
        ),
    ]
